### ISSUE TITLE
Universe Minimization ToSet

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#811] opened 2016-06-12 16:33 UTC
In https://github.com/HoTT/HoTT/blob/master/theories/Basics/Overture.v
Define Type₁ (really, Type_i for any i > 0) so that we can enforce having universes that are not Set.  In trunk, universes will not be unified with Set in most places, so we want to never use Set at all.

However, https://coq.inria.fr/refman/Reference-Manual032.html#sec783
The option Unset Universe Minimization ToSet disallows minimization to the sort Set and only collapses floating universes between themselves.

Is this still correct? Wouldn't using Set simplify matters with this minimization?

@mattam82 ?

**Comment by spitters** [comment] 2016-06-21 10:48
This is related to https://github.com/HoTT/HoTT/issues/774
```
Unset Universe Minimization ToSet 
```

seems to be the Unset Aggressive Universe Minimization that @jasongross was asking about.
Can we now put Empty and Unit in Set as @peterlefanulumsdaine  asked. 
My impression is that it would simplify things.

This universe inconsistency is related too:
https://github.com/HoTT/HoTT/issues/754

**Comment by mikeshulman** [comment] 2016-06-23 22:45
Anyone who wants to try putting Empty and Unit into Set, please do!  Probably some universe annotations will have to be removed here and there, in places that currently acquire an extra universe parameter due to occurrences of Unit.

**Comment by SkySkimmer** [comment] 2016-06-24 13:23
Looking into it: https://github.com/SkySkimmer/HoTT/tree/empty-unit-in-type0
Bunches of results about Empty/Unit have to be made polymorphic through annotations, since universe cumulativity doesn't go through inductive types.
ie when defining `Unit : Type0` we get `Unit : Type1`, but when we define `unit_contr : Contr@{Type0} Unit` we don't get `unit_contr : Contr@{Type1} Unit`, so instead I define `unit_contr : Contr@{i} Unit`.
The other solution would be to define a lift function `lift@{i j, i < j} : forall A, Contr@{i} A -> Contr@{j} A` but it would have to be defined for pretty much every inductive type, and I have no idea how it would behave with typeclass resolution.

Fixing stuff is not trivial because you have to figure out that some random error or instance resolution failure is due to some specific definition somewhere which isn't polymorphic enough.
At least doing it while in the process of changing Unit from Type1 to Type0 means you know why things are failing, but I don't know how practical proving new things would be. It depends on how often random failures would get produced in this way.

**Comment by spitters** [comment] 2016-06-24 13:45
@amintimany might be interested in this.

**Comment by JasonGross** [comment] 2016-06-24 13:52
@SkySkimmer glancing at your code, it seems like you forgot `Global Unset Universe Minimization ToSet` in Overture.v.  Does doing this make most things just work without your other extra annotations?

**Comment by amintimany** [comment] 2016-06-24 14:25
As Jason says you should put `Global Unset Universe Minimization ToSet` somewhere at the beginning of the development (somewhere that is imported (almost) everywhere) like in Overture.

Working with lifts in general is a hassle. In this case, it is even more so. The problem is that not only do you have use a lift whenever you use a definition, say `A`, that causes a collapse to `Set`, but also any time that use `A` to define `B` and so on. This situation is illustrated in [https://gist.github.com/amintimany/7c39368ea168a62b0dc4](https://gist.github.com/amintimany/7c39368ea168a62b0dc4). I wrote this back when I was using 8.5~beta2 but I presume if you don't `Unset Universe Minimization ToSet` the issue should still be present in 8.5 and 8.5pl1.

**Comment by SkySkimmer** [comment] 2016-06-24 14:52
https://github.com/SkySkimmer/HoTT/tree/empty-unit-in-type0-no-minim
I was afraid that it would make things slow but that hasn't happened yet.
OTOH I'm getting a universe annotation length in Modalities/Nullification.v and I don't have a clue how to fix it.

**Comment by mikeshulman** [comment] 2016-06-24 20:34
Could you work on it in a branch with no other differences from master please?

**Comment by SkySkimmer** [comment] 2016-06-27 10:52
https://github.com/SkySkimmer/HoTT/tree/empty-unit-in-type0-no-minim is now based on master and everything compiles.
I ended up locally enabling minimisation to set in Idempotents (because it was generating bunches of universes somewhere) and in contrib/HoTTBookExercises (for one lemma which was doing something weird and failing at the save step with a type mismatch error).
This lemma https://github.com/SkySkimmer/HoTT/commit/a7237d7a76cf6160c93e78ac609fc403710be213#diff-2b9b3c01706927c8aa694a3df9f91cd5R89 had something weird happen where defining it with := created an extra universe but doing the same thing with tactics just worked.
This lemma https://github.com/SkySkimmer/HoTT/commit/a7237d7a76cf6160c93e78ac609fc403710be213#diff-4f44d4d3c0e77bd1bcfbc3385e2248f5R138 produced a bunch of universes and seemed hard to track them down so I made an auxiliary definition then collapsed the extra universes with an annotation.

Other than that it was just fixing up universe annotations here and there.

**Comment by spitters** [comment] 2016-06-28 12:02
While we are discussing this [3807](https://coq.inria.fr/bugs/show_bug.cgi?id=3807), 3811 and 3825 have been fixed, but 
https://github.com/HoTT/HoTT/blob/master/theories/Modalities/Modality.v
still contains workarounds. I have not had the time to look at this yet.

**Comment by mikeshulman** [comment] 2016-06-28 22:05
#779, #816.  Are we working around bug 3825?

**Comment by spitters** [comment] 2016-06-29 09:09
The comments say that we are working around 3825.

**Comment by mikeshulman** [comment] 2016-06-29 17:56
#817

**Comment by mikeshulman** [comment] 2016-06-29 20:15
I think the main issue here is closed by #813 .

**Closed by mikeshulman** 2016-06-29 20:15 UTC
