### ISSUE TITLE
Universe inconsistency with equiv_induction?

### ISSUE THREAD

**Issue by normalchaos** [HoTT/HoTT#754] opened 2015-05-08 23:52 UTC
I have encountered a rather weird bug today when using equiv_induction tactic. Coq claims universe inconsistency, but the code looks innocuous to me.

Require Import HoTT.
Definition nat_discr {n: nat}: 0 <> S n.
  intro p.
  equiv_induction (@equiv_path_nat 0 (S n)).

In nested Ltac calls to "equiv_induction" and
"refine ((fun g H B e => respects_equivalenceL.1 B e g) _ _)" , last call failed. Error:
In environment n : nat; g : ?T; H : ?T0; B : ?T1; e : ?T2
The term " fun (P : Type0)  (_ : 0 =n n.+1 <~> P) => P -> Empty" has type
 "forall P : Type0, 0 =n n.+1 <~> P -> Type" while it is expected to have type
 "forall B0 : Type, ?T3 <~> B0 -> Type" (universe inconsistency).

**Comment by JasonGross** [comment] 2015-05-09 17:13
It does look rather innocuous, doesn't it.  The bane of `Type0` (of `Set`) strikes again.  @mikeshulman, can you provide input on the right route to take here?  If move `Type1` to `Coq.Init.Datatypes`, and put `nat` in `Type1`, then I get a complaint that `ExtendableAlong` needs 5 universe arguments (and I'm not sure what impact this has on other things, like the rest of modalities, or performance, so I didn't touch it).  If I give `nat` a global `Universe` that is above `Set`, then I get complaints about mismatched module and signature universes (because the signature doesn't say things about the relation of universes to this universe of `nat`'s).  I'm going to see if I can make `equiv_induction` robust in the face of `Set` (maybe with a sprinkling of `uconstr`s), but we might want to move `nat` out of `Set` like we moved `unit`, too.

**Comment by JasonGross** [comment] 2015-05-09 18:56
Here's the issue: `Empty` lives strictly above `Set`, while `@paths nat` defaults to living in `Set`, in a way that can't be bumped up.  Intuitively, what you want to do here is make the types on both sides of the equivalence live in the same universe, and this universe needs to be big enough to contain the identity equivalence at the type on the left (because `equiv_induction` is left-biased).  This would be fine if you were using `((@equiv_path_nat O (S n))^-1)%equiv`; we would generalize the `Empty` type to any type strictly larger than `Set`, and the identity equivalence at `0 = n.+1` can be enlarged to live in this type of equivalences.  However, with `@equiv_path_nat O (S n)`, we instead generalize  `0 = n.+1` to an arbitrary `Set`, and ask the identity equivalence at `Empty` (which is strictly larger than `Set`) to live inside this type---it doesn't work!  Since the reflexivity proof isn't well-typed, we can't apply induction.  We could try to do some kind of ad-hoc universe-level surgery, but I don't think there's a nice way to do this, nor even a way to do this in general.

I'm going to make a partial fix for some side-issues with `equiv_induction` that came up in debugging this, but I think the answer here is to make `nat` live in `Type1` (which I'd like to delegate to you, @mikeshulman, if you're ok with that), and the workaround is to do `equiv_induction ((@equiv_path_nat O (S n))^-1)%equiv`.

**Comment by mikeshulman** [comment] 2015-05-11 23:25
I don't understand.  Why can't `equiv_induction` deal with equivalences between types in two different universes?

**Comment by JasonGross** [comment] 2015-05-11 23:46
I think it is roughly the same reason that you cannot show `A = B :> Type@{i} -> A = B :> Type@{j}` for `j < i` (and `A : Type@{j}`, `B : Type@{j}`) without univalence.  Although the endpoints fit in the universes, the intermediate types might not.  Does that make any sense?

**Comment by mikeshulman** [comment] 2015-05-12 05:47
I don't see yet how that affects `equiv_induction`.

**Comment by JasonGross** [comment] 2015-05-12 11:40
Let me try a different tack.  Equivalence induction is done with families over `{ B : Type@{j} | Equiv@{i j} A B }` for fixed `A`.  Take `A = Set` and `j = Set`, so that we have a family over `{ B : Set | Equiv@{i Set} Set B }`.  Perhaps we have turned on `-impredicative-set`, so that it is important that our type family be getting a `Set` as its type.  Now note that the identity equivalence does not fit unless we have `Set : Set`, so we cannot even state a well-typed principle of equivalence induction, much less prove it.

**Comment by mikeshulman** [comment] 2015-05-13 23:06
I agree that equivalence induction is only provable when your family is big enough to include the identity.  Are you saying you nevertheless expect it to be true in some other cases?

**Comment by mikeshulman** [comment] 2015-05-13 23:09
Would it help if we allowed `equiv_idmap` to have type `Equiv@{j k}` for distinct `j` and `k`?

**Comment by JasonGross** [comment] 2015-05-13 23:21
When it just so happens that it doesn't matter which side of the equivalence you hold constant, or when your type family is appropriately level-polymorphic (e.g., the family is `fun T (e : Equiv ... T) => T`), then we can do an ad-hoc generalization of whatever Coq gives us as the default family.

I do not think a generalized `equiv_idmap` would help here, though it might help in other cases; I think the issue is that `@paths nat` lands in `Set` by default (and thus here).

**Comment by mikeshulman** [comment] 2015-05-14 06:10
Okay, I think I'm starting to see the issue.  What about inserting a `lift` somewhere if necessary, would that help?

I'm resisting putting `nat` in `Type1` not because I don't agree that it's the right thing to do in principle (I do), but because I don't want to chase all the extra universe parameters throughout modalities that such a change would probably entail; and, as you suggested, I'm worried about performance.

**Comment by mikeshulman** [comment] 2016-06-29 20:18
This is probably fixed by #813?

**Comment by Alizter** [comment] 2019-11-20 13:13
This seems to work now so closing. Unless it still doesn't, then please reopen.

**Closed by Alizter** 2019-11-20 13:13 UTC
Labels: bug, universe inconsistency, universe polymorphism
