### ISSUE TITLE
Anomaly when one uses Record synonyms in Context.

### ISSUE THREAD

**Issue by georgydunaev** [HoTT/HoTT#801] opened 2016-04-21 08:15 UTC
I tried to reproduce this bug in standart coq, but I didn't have a success.
_Anomaly: Uncaught exception Type_errors.TypeError( _, _). Please report._
All lines are essential.
```
Require Import HoTT.
Require HoTT.categories.
Require Import Category.Core Category.Morphisms.
Require Import HoTT.categories.SimplicialSets.

Section my.
Context `{Funext}.
Definition sset := simplicial_set.
Context (A B:simplicial_set).
Context (f:morphism sset A B).
Theorem anomaly:PreCategory.  
```

**Comment by mikeshulman** [comment] 2016-04-21 08:59
Anomalies are always Coq bugs (to report at Coq bugzilla), whether or not they occur in standard Coq --- but of course the coqdevs prefer a MWE that doesn't require all of HoTT.categories.  (-:  Have you tried guessing+testing what more specifically might be the problem?

**Comment by mattam82** [comment] 2016-04-21 09:51
I do have a complete Coq+HoTT around, but I cannnot reproduce this with 8.5 or 8.5pl1.

**Comment by georgydunaev** [comment] 2016-04-21 09:58
I've isolated bug from HoTT.

Record qq:={
 obj : Type
}.
Section my. (*anomaly depends on this line*)
Context (ww:qq).
Definition ss := ww .
Context (A: obj ss).
Theorem anomaly:nat.

I you have no such bug, maybe I should reinstall the system. (it was last installed 3 weeks ago)

(reported https://coq.inria.fr/bugs/show_bug.cgi?id=4686)

**Comment by mattam82** [comment] 2016-04-21 10:09
Which version of Coq are you using? (coqtop or coqc --version, or hoqtop/hoqc --version)

**Comment by georgydunaev** [comment] 2016-04-21 10:32
8.5beta2

**Comment by georgydunaev** [comment] 2016-04-21 10:35
8.5beta2
I also have different variant of traditional Coq 8.4. May it's installation with default parameters somehow break or corrupt the integrity of Hoq?

**Comment by mattam82** [comment] 2016-04-21 10:38
I guess the bug was fixed since then

**Comment by mattam82** [comment] 2016-04-21 10:39
The bug is not triggered in 8.4(pl6) either

**Comment by mikeshulman** [comment] 2016-06-28 21:59
Closing since it appears this bug no longer appears in a recent coq.

**Closed by mikeshulman** 2016-06-28 21:59 UTC
