### ISSUE TITLE
Automatically infering Truncation levels

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#862] opened 2017-04-13 09:56 UTC
I recall that the following worked before. I think I am overlooking something.
```
Require Import HoTT Bool.
Check (Bool:hSet).
(*  The term "Bool" has type "Type1" while it is expected to have type "hSet".
The relevant infrastructure is here:
Canonical Structure default_TruncType := fun n T P => (@BuildTruncType n T P).
Creating the following does not help:
Instance hset_bool : IsHSet Bool.*)
```

E.g. it worked here:
https://github.com/HoTT/HoTT/commit/c1540bc49830b3149e16a49220148138546ae55a

**Comment by Alizter** [comment] 2019-11-20 13:15
Hmm, this still doesn't work. This is the first time I am seeing canonical structures however. I asked about something similar in #1071. Does anybody know how to get this working again?

**Comment by mikeshulman** [comment] 2019-11-20 14:29
Has anyone tested and found that this actually did used to work?  I don't have any memory of it ever working.

**Comment by Alizter** [comment] 2021-04-12 22:04
I'm closing this issue since we haven't been able to reproduce it. However there is recent interest in typeclass guided coercions which would allow coercions coming from Sortclass: https://coq.discourse.group/t/generalizing-coercions-to-infer-typeclass-arguments/1241

Feel free to reopen if this is still an issue.

**Closed by Alizter** 2021-04-12 22:04 UTC
Labels: bug, regression
