### ISSUE TITLE
Compiling HoTT with recent coq

### ISSUE THREAD

**Issue by SkySkimmer** [HoTT/HoTT#804] opened 2016-05-19 11:53 UTC
I want to experiment with @mattam82's Inductive-Inductive definitions (https://github.com/mattam82/coq/tree/IR) and HoTT, but HoTT doesn't compile and immediately complains:

```
COQTOP coq/theories/Init/Notations
File "./coq/theories/Init/Notations.v", line 88, characters 0-26:
Error: File not found on loadpath : eauto.cmxs
Loadpath: ./coq/theories:.:~/HoTT/coq-HoTT/ide/utils:~/HoTT/coq-HoTT/ide/MacOS:~/HoTT/coq-HoTT/ide:/usr/share/coq:./coq/plugins/omega:./coq/plugins/rtauto:./coq/plugins/firstorder:./coq/plugins/cc:./coq/plugins/extraction:./coq/plugins/micromega:./coq/plugins/romega:./coq/plugins/quote:./coq/plugins/xml:./coq/plugins/btauto:./coq/plugins/nsatz:./coq/plugins/fourier:./coq/plugins/derive:./coq/plugins/decl_mode:./coq/plugins/syntax:./coq/plugins/funind:./coq/plugins/setoid_ring:./coq/plugins:./coq/toploop:./coq/stm:./coq/dev
Makefile:904: recipe for target 'coq/theories/Init/Notations.vo' failed
make: *** [coq/theories/Init/Notations.vo] Error 1
```

The error is the same with coq trunk. IR appears to have been branched after https://github.com/mattam82/coq/commit/a581331f26d96d1a037128ae83bebd5e6c27f665 (which might be related to the problem since it moves eauto around).

**Comment by andrejbauer** [comment] 2016-05-19 16:37
Right, it's likely that `Notations.v` is not compatible with that branch of Coq. One possibility is that you create an `IR` branch of HoTT and just do whatever is needed. The files in `coq/theories` exist only because without them Coq is unahppy. So, if everyone is happy without `eauto` you can just delete it.

**Comment by spitters** [comment] 2016-05-19 18:17
Since this also shows up in trunk. It would be good to have a more informed
solution.
I am not sure whether we use eauto, so perhap you can check this and if
not, comment it out.

**Comment by SkySkimmer** [comment] 2016-05-19 18:23
eauto appears a bunch of times in theories/categories/, a few times in contrib/ and a small number of times elsewhere:
```
contrib/Freudenthal.v
82:  { apply @trunc_sigma; try typeclasses eauto.
83:    { apply @trunc_forall; try typeclasses eauto; intro.
84:      apply @trunc_arrow; try typeclasses eauto; intro.
89:  { apply @trunc_arrow; try typeclasses eauto; intros.

contrib/HoTTBookExercises.v
647:      typeclasses eauto.
962:    try typeclasses eauto.

coq/theories/Init/Notations.v
88:Declare ML Module "eauto".

coq/theories/Program/Tactics.v
333:Ltac program_simpl := program_simplify ; try typeclasses eauto with program ; try program_solve_wf.

etc/dpdgraph-0.4alpha/tests/Test.v
337:    injection H; clear H; intros; f_equal; eauto.
911:    eauto.
1083:  induction 1; simpl; auto; eauto.

STYLE.md
378:(You can usually also use `typeclasses eauto` or `eauto with

theories/Tactics/BinderApply.v
107:  (** Alternatively, we can make [A] explicit.  But then we get an error about not being able to resolve the instance of [Funext].  We can either tell Coq to solve the side condition using the [assumption] tactic (or [typeclasses eauto], for that matter), or we can have typeclass inference run when we construct the lemma to apply. *)
120:  binder apply @path_forall in H' using typeclasses eauto.

theories/Types/Sum.v
830:  try typeclasses eauto;
934:  typeclasses eauto.

theories/HSet.v
138:  eauto.

theories/hit/quotient.v
87:    apply @equiv_iff_hprop; eauto.

theories/categories/Cat/Core.v
60:    typeclasses eauto.
68:    typeclasses eauto.

theories/categories/Structure/Core.v
126:  split; repeat intro; eauto with structure_homomorphisms.
128:  eauto with structure_homomorphisms.
151:  try typeclasses eauto.

theories/categories/GroupoidCategory/Core.v
75:  typeclasses eauto.

theories/categories/HomotopyPreCategory.v
68:                 typeclasses eauto

theories/categories/InitialTerminalCategory/Functors.v
91:    typeclasses eauto.

theories/categories/FunctorCategory/Core.v
35:  typeclasses eauto.

theories/categories/LaxComma/CoreParts.v
85:      typeclasses eauto.
161:      typeclasses eauto.

theories/categories/LaxComma/Core.v
84:  typeclasses eauto.
110:      typeclasses eauto.

theories/categories/SetCategory/Morphisms.v
154:  typeclasses eauto.
163:  typeclasses eauto.

theories/categories/Pseudofunctor/RewriteLaws.v
71:          [ typeclasses eauto
73:            [ eapply iso_whisker_r; typeclasses eauto
74:            | typeclasses eauto ] ] ] ].

theories/categories/Adjoint/Paths.v
46:    typeclasses eauto.

theories/categories/NaturalTransformation/Paths.v
43:    typeclasses eauto.

theories/categories/Functor/Attributes.v
61:    typeclasses eauto.
69:    typeclasses eauto.
82:    apply H'; eauto.
99:    eauto.

theories/categories/Functor/Paths.v
171:    typeclasses eauto.

theories/categories/Comma/Core.v
89:      typeclasses eauto.
169:      typeclasses eauto.
195:      typeclasses eauto.
280:  typeclasses eauto.
302:      typeclasses eauto.

theories/categories/CategoryOfSections/Core.v
68:  typeclasses eauto.

theories/categories/FundamentalPreGroupoidCategory.v
72:                 typeclasses eauto

theories/categories/UniversalProperties.v
35:          | by typeclasses eauto ].

theories/categories/Category/Pi.v
49:  typeclasses eauto.

theories/categories/Category/Univalent.v
28:  typeclasses eauto.

theories/categories/Category/Sum.v
57:      typeclasses eauto

theories/categories/Category/Prod.v
42:  typeclasses eauto.

theories/categories/Category/Morphisms.v
126:    typeclasses eauto.

theories/categories/NatCategory.v
28:    induction n; [ typeclasses eauto |].
29:    induction n; [ typeclasses eauto |].
31:      typeclasses eauto.

```

**Comment by JasonGross** [comment] 2016-05-19 22:34
Maybe we can just copy/symlink the `Notations.vo` file from the installation, rather than having our own?

**Comment by andrejbauer** [comment] 2016-05-20 06:01
No. We cannot rely on anything that wasn't compiled with `--indices-matter`.

**Comment by JasonGross** [comment] 2016-05-20 06:11
I think 8.5 installs .v files and not just .vo files, so perhaps we can copy the .v file?  The issue is not "fixing eauto" but "writing code that works with multiple versions of Coq at the same time", which is often tricky, even more so with OCaml plugins.

**Comment by andrejbauer** [comment] 2016-05-20 08:35
We're not really interested in supporting multiple versions of Coq, are we? @SkySkimmer is trying to experiment with some experimental branch of Coq, so he can just make a branch for himself. There's no point in trying to find a global solution to this problem, IMHO. Or to put it better, the global solution is for Coq to give us support for ripping out the standard library in a controlled manner.

**Comment by spitters** [comment] 2016-05-20 08:38
One version of Coq will keep us busy as it is. However, I am worried that trunk breaks. This means we will have to deal with it at some point. @mattam82 any advice?

**Comment by SkySkimmer** [comment] 2016-05-20 09:08
eauto seems to have become not a plugin so just removing its declaration seems to work.
There are some other breaks. One is trivial syntax like
```
--- a/coq/theories/Program/Tactics.v
+++ b/coq/theories/Program/Tactics.v
@@ -258,7 +258,7 @@ Ltac autoinjection tac := idtac.
 
 Ltac inject H := progress (inversion H ; subst*; clear_dups) ; clear H.
 
-Ltac autoinjections := repeat (clear_dups ; autoinjection ltac:inject).
+Ltac autoinjections := repeat (clear_dups ; autoinjection ltac:(inject)).
 
 (** Destruct an hypothesis by first copying it to avoid dependencies. *)

```

The other is that the `symmetry` tactic is broken for some reason, although replacing its uses by `apply symmetry` has worked so far.

**Comment by mattam82** [comment] 2016-05-20 09:50
There's a few breaking changes in trunk indeed, but nothing wild a priori. If needed I can easily rebase my branch on the current trunk if you want to follow it.

**Comment by SkySkimmer** [comment] 2016-05-20 10:54
It's mostly working in https://github.com/SkySkimmer/HoTT/tree/with-IR
There's an issue with notation scoping which had me make changes like https://github.com/SkySkimmer/HoTT/commit/8a75ddf48fce91afeb936e5460a89f86e77dea34#diff-2a876903badfeee02051b33c7e5e4e1dL177
It also comes up a lot in the category files (with `->` getting interpreted as `functor_category` or something when non dependent type product is desired) so I'm leaving them broken for now.

**Comment by SkySkimmer** [comment] 2016-05-23 11:23
@mattam82 found a bug in your branch when running with -indices-matter.
```
Local Inductive A : Type :=
with B : A -> Type :=.
```
produces `Anomaly: Uncaught exception Term.DestKO. Please report.`

**Comment by mattam82** [comment] 2016-05-27 11:45
@SkySkimmer alright, noted.

**Comment by mattam82** [comment] 2016-05-27 12:56
@SkySkimmer and fixed

**Comment by mattam82** [comment] 2016-05-27 13:03
I think the %type annotations are strange, is -> redefined in HoTT such that both sides would not necessarily be parsed in type_scope? The changes might be related to @JasonGross 's reinstatment of the scopes+coercions patch.

The minor ltac:() change is not decided yet, the universe annotations on hProp should become cleanly supported and the symmetry breakage sounds like a bug.

**Comment by SkySkimmer** [comment] 2016-05-27 13:18
@mattam82  This file https://github.com/SkySkimmer/HoTT-algebra/blob/error/error.v is giving me uncaught Not_found when ending the section.

**Comment by JasonGross** [comment] 2016-05-27 14:33
I think the issue with `type_scope` is that it needs to be explicitly bound to `Sortclass`.  If you replace `Notations.v` with the one in the standard library from the version of Coq you're using, I suspect most of these incompatibilities will go away

**Comment by mattam82** [comment] 2016-05-27 15:49
Ha, that's surely possible, I did not try sections yet, and they're terrible for inductives.

**Comment by mattam82** [comment] 2016-05-29 19:14
@SkySkimmer I fixed the section issue (I hope).

**Comment by ejgallego** [comment] 2016-06-02 15:42
Hi,

I've setup a branch to investigate compilation of HoTT with Coq trunk, as 8.6 is planned to happen soon.

https://github.com/ejgallego/HoTT/tree/coq-trunk-draft

The current blocking issue is:

```
File "./theories/Modalities/Accessible.v", line 277, characters 4-12:
Error: Universes {HoTT.Modalities.Accessible.783
HoTT.Modalities.Accessible.757} are unbound.
```
this has to be investigated by @mattam82 I guess.

Some other easier to solve issues are:

- Error in `Notations.vo`, etc...  The correct solution is on my tree. I suggest having two folders coq-8.5 and coq-8.6 and symlinking the proper one as appropriate.
- `symmetry` doesn't properly work; in a couple of cases rewrite also fails.

**Comment by SkySkimmer** [comment] 2016-06-02 15:44
Sounds similar to https://coq.inria.fr/bugs/show_bug.cgi?id=4769

**Comment by ejgallego** [comment] 2016-06-02 15:45
Indeed, I just saw it. @mattam82 , this also looks suspicious as the number of universes seems to have changed: https://github.com/SkySkimmer/HoTT/commit/4c813e55c650243924088250ebfa71a53d56ff4f

**Comment by ejgallego** [comment] 2016-06-02 15:47
Is the `symmetry` -> `apply symmetric` supposed to happen in 8.6 or it is a Coq bug?

**Comment by JasonGross** [comment] 2016-06-02 19:15
How soon is 8.6 supposed to happen?

> Sounds similar to https://coq.inria.fr/bugs/show_bug.cgi?id=4769

No, @ejgallego 's issue is different.  [bug 4769](https://coq.inria.fr/bugs/show_bug.cgi?id=4769) is an anomaly, somehow related to unused section variables (Changing `Variables B C D E : PreCategory.` to `Variables C D E : PreCategory.` in [my minimized example](https://coq.inria.fr/bugs/show_bug.cgi?id=4769#c1) makes the anomaly go away.  @ejgallego 's issue is related to @mattam82 's fix to [bug 4527](https://coq.inria.fr/bugs/show_bug.cgi?id=4527), I believe.

No idea what's going on with `symmetry`, but note that we redefine the `symmetry` tactic in `Basics/Overture.v`:
```coq
(** Even if we weren't using [cbn], we would have to redefine symmetry, since the built-in Coq version is sometimes too smart for
its own good, and will occasionally fail when it should not. *)
Ltac symmetry :=
  let R := match goal with |- ?R ?x ?y => constr:(R) end in
  let x := match goal with |- ?R ?x ?y => constr:(x) end in
  let y := match goal with |- ?R ?x ?y => constr:(y) end in
  let pre_proof_term_head := constr:(@symmetry _ R _) in
  let proof_term_head := (eval cbn in pre_proof_term_head) in
  refine (proof_term_head y x _); change (R y x).
```

**Comment by ejgallego** [comment] 2016-06-02 23:05
Cool, thanks for the pointers Jason, hopefully we get HoTT running in 8.6 soon!

I can't comment officially, but my personal impression is that Coq devs are trying to get a more lively release schedule going on for Coq, maybe a couple of times a year? Also, they are monitoring a lot of developments to ensure no breakage happens, however HoTT is still not in coq-contribs but hopefully I'll happen soon ( coq-contribs/coq-contribs#2 )

**Comment by spitters** [comment] 2016-06-07 19:28
This is related to #694 and #424 .

**Comment by SkySkimmer** [comment] 2016-06-30 09:35
@JasonGross I looked again into the symmetry thing and noticed that when the ltac it says
`The Ltac name symmetry may be unusable because of a conflict with a notation.`
So Coq has claimed that name for itself.
The change happened at https://github.com/coq/coq/commit/ae3bbff3ca2564fe24bdf3dd517c82807eae9151 (tested `Ltac symmetry := idtac. Goal Type. symmetry.` before and after that commit).

**Comment by ejgallego** [comment] 2016-06-30 09:47
Umm, @SkySkimmer , this may be something for @ppedrot to have a look at when he can.

**Comment by spitters** [comment] 2016-09-02 10:45
@ejgallego With 8.6 nearing, what is the status of this? My impression is that coq-contribs may be abandoned in favor of opam.

**Comment by ejgallego** [comment] 2016-09-08 23:57
@spitters I have no clue what the current status is, will hopefully check again someday soon; many bugs have been fixed so it should work better, maybe @JasonGross knows better?

Regarding coq-contribs, I'll ask in the next Coq WG.

**Comment by JasonGross** [comment] 2016-09-27 15:38
I'm not up to date on HoTT + v8.6.  What happens if we replace `Ltac symmetry := ...` with `Tactic Notation "symmetry" := ...`?

**Comment by ppedrot** [comment] 2016-09-27 15:38
It should work. But you can probably redefine it as `Ltac symmetry := ...` as well.

**Comment by ejgallego** [comment] 2016-09-27 16:00
You will also need `Global Unset Bracketing Last Introduction Pattern.` , then you can get quite far on 8.6, however the scary universe issues seem still there.

**Comment by mattam82** [comment] 2016-10-07 14:44
None of Notation "symmetry" or Ltac symmetry ::= seems to work... The error is: Ltac call to "symmetry (clause_dft_concl)" failed which seems to indicate it's still ignoring the redefinition.

**Comment by ppedrot** [comment] 2016-10-07 14:47
Aha... That's a parsing issue... Coq believes that `symmetry` is `symmetry ∅` where `∅` is the empty `in` clause. I'll have a look at a solution.

**Comment by mattam82** [comment] 2016-10-07 15:17
@ppedrot I don't want to charge you but appart from that one, another change in Ltac makes the tactics in theories/Tactics/RewriteModuloAssociativity.v fail (see the examples at the end of it in branch
https://github.com/mattam82/HoTT.git branch v8.6) so I cannot get to my universe bugs :)

**Comment by ppedrot** [comment] 2016-10-07 15:25
Hmm, I have definitely no idea of the reason of the failure... Digging into it :/

**Comment by mattam82** [comment] 2016-10-07 15:48
Nevermind, it's my fault, I introduced the issue

**Comment by ppedrot** [comment] 2016-10-07 15:50
Glad to be aware of that. I was really about to post a rant about Ltac semantics right here... Seeing the kind of Ltac stuff used by HoTT, I'm really worried about the overall correction and maintenance of this pile of hacks...

**Comment by JasonGross** [comment] 2016-10-07 16:36
You can blame the Ltac hackery on me.    I'm open to better ways of accomplishing the same thing that don't rely on plugins.  You might also want to take a look at my contribution to https://github.com/coq/coq/pull/247/commits.

**Comment by mattam82** [comment] 2016-10-07 16:37
Ok, now I'm getting into the universe changes, I'll report here on my progress.

**Comment by mattam82** [comment] 2016-10-10 16:33
https://github.com/HoTT/HoTT/pull/831 has it all. In the end it's approximately 30 lines of annotation changes, but some of those can actually be dropped now (less useless universe quantifications around).

**Comment by mattam82** [comment] 2016-10-10 16:36
The _ -> _ issues are gone with the proper annotation in Init/Notations.v btw.

**Comment by mattam82** [comment] 2016-10-10 16:37
I'll get to rebasing the IR branch on 8.6 once we settle this.

**Comment by ejgallego** [comment] 2017-04-19 20:40
@jason this needs to be closed.

**Comment by JasonGross** [comment] 2017-04-19 20:41
Closed by #863

**Comment by SkySkimmer** [comment] 2017-04-19 20:50
#863 doesn't fix compilation with trunk. Is there any hope of compiling the same branch with 8.6 and trunk?

**Comment by JasonGross** [comment] 2017-04-19 21:11
Not without changing how we interact with Coq; there's not way to have the same `Notations.v` file compatible with both 8.6 and trunk; so we'd either need to dynamically create `Notations.v`, or pull it from the Coq distribution, or give up on using most of Ltac.

**Comment by ejgallego** [comment] 2017-04-19 21:29
Indeed sorry, maybe we should open a different issue for 8.7 support?

**Comment by ejgallego** [comment] 2018-10-11 14:38
This should be closed; I lack the permission to do so, please, some maintainer do.

**Closed** 2018-10-11 15:32 UTC
