### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#1057] opened 2019-07-26 07:20 UTC
I got a request on using HoTT with coqide on Windows.
@JasonGross are you aware of any progress ?
Alternatively, we can suggest them to use jscoq, but we would need to ask @ejgallego to update it to a recent version.

**Comment by kristinas** [comment] 2019-07-26 19:13
I sent an email to @ejgallego, hopefully he can get back to me.

**Comment by JasonGross** [comment] 2019-07-26 19:43
I haven't used CoqIDE on Windows in quite a while, so I'm not sure.

**Comment by kristinas** [comment] 2019-07-26 19:43
Ok, we are moving towards using JsHoTT so I suppose the issue is moot now. Thanks Bas and Jason!

**Comment by Alizter** [comment] 2019-07-27 07:22
The latest versions of windows 10 have the inbuilt linux kernel. It may be possible in the future to build everything on that. That would somewhat count as support for windows.

**Comment by JasonGross** [comment] 2019-07-27 20:28
Last I checked the Linux subsystem did not support non-terminal graphical apps.

**Comment by mikeshulman** [comment] 2019-07-27 21:11
Why not use Emacs+ProofGeneral?  Last I checked Emacs works just fine on Windows.

**Comment by Alizter** [comment] 2019-07-28 07:17
I think Kristina is looking for the easiest solution to teach usage of the library on. Emacs is generally, in my experience, a steep learning curve. I think it is a sensible idea to use CoqIDE for such a task. But it looks unlikely that will be working on windows anytime soon.

It would however be not too bad if Emacs+ProofGeneral was used with some effort put into how to use it. Perhaps a cheatsheet of frequently used keyboard commands, and how Emacs works? I don't doubt that once you learn Emacs it is a fine way of using the library (if not better).

**Comment by mikeshulman** [comment] 2019-07-28 14:37
Learning all the ins and outs of Emacs is a long process and never complete (I just learned a new trick last week).  But you don't need any of the fancy stuff just to edit files; you just type stuff.  (Unlike, say, vi.)  You don't even need to know any key commands; there are graphical menus.  I guess for ProofGeneral you probably need to know a couple key commands since you don't want to be going to the menus every time you want Coq to process a line, but that's true in CoqIDE as well; in fact I think many of CoqIDE's commands were copied from Emacs.

Using Coq in a browser is okay for the duration of a tutorial, I guess, but if the aim is to teach the students to be successful long-term users of Coq in their own right, it would be much better to set them up with an install on their own computers.

**Comment by kristinas** [comment] 2019-07-28 15:11
I think learning how to formalize homotopy type theory in Coq vs. installing Coq/learning how to use Emacs are two orthogonal issues. Given the short amount of time we have, I prefer not to spend too much time on the latter issue... anybody can learn how to use Emacs on their own, if that is the editor of choice for them. I personally never liked Emacs and stay away from it as long as there is another option (like CoqIDE).

**Comment by Alizter** [comment] 2019-07-28 16:30
@kristinas Are you absolutely bound to Windows? Working in linux would be much easier for what you are doing.

**Comment by kristinas** [comment] 2019-07-28 16:35
@Alizter If you mean for my own development, not for the course itself, then Windows is my preference for everything else except Coq, which is literally the only reason why I even have a Linux distribution on my PC.

**Comment by mikeshulman** [comment] 2019-07-28 21:35
Learning to use ProofGeneral inside Emacs should be no more difficult than learning to use CoqIDE.  Of course you don't want to spend a long time on installation during the actual school; I was assuming you were trying to get everyone to do the install before the summer school so they'd be all set up.  Given that installation can be one of the significant hurdles to get people over before they can actually start using Coq on their own, I think it would be worth some effort.

**Comment by kristinas** [comment] 2019-07-28 22:29
There is an installation party taking place the afternoon before the actual school, and we are also sending out instructions on how to install HoTT Coq on Linux. However, I don't know that we can reasonably expect everyone to be up and running by the time the school starts. 

I don't know how well HoTT Coq works on Macs (according to Steve, quite poorly) but as of now, I don't believe Windows is a good option for people wanting to do some serious formalization, regardless of which editor they want to use (this is pretty much what @Alizter was saying too I think). 

So we want to encourage people serious about Coq to eventually obtain a Linux distribution and get Coq set up properly. The instructions on GitHub are very clear and I don't think the installation presents a significant hurdle there - even I can do it. But all of this is not likely to happen before the course for people with Windows and Macs.

**Comment by mikeshulman** [comment] 2019-07-28 22:48
Fair enough, I suppose.  I'm all in favor of people obtaining a Linux.

**Comment by MSoegtropIMC** [comment] 2019-07-30 13:08
I would say this is solved and can be closed. Preliminary Coq Windows installers including HoTT and batch files to call e.g. CoqIDE with the correct parameters can be found here:
[64-bit](https://gitlab.com/coq/coq/-/jobs/261177798/artifacts/browse/artifacts/)
[32-bit](https://gitlab.com/coq/coq/-/jobs/261177800/artifacts/browse/artifacts/)
This will be included in Coq 8.10 or 8.10.1.
See the discussion in #1058

**Comment by spitters** [comment] 2019-07-30 13:13
Before closing this, it would be good to update INSTALL.md
I'm not a windows user, so it would be good if someone else would write that.

Thanks for all the progress on this!

**Comment by MSoegtropIMC** [comment] 2019-07-30 13:24
> Before closing this, it would be good to update INSTALL.md
> I'm not a windows user, so it would be good if someone else would write that.

I thought it is better to do this after it is included in a release Coq Installer. But since you have a big HoTT event upcoming, I guess it would be better to do a preliminary version now. Expect my PR soon. The disadvantage of the preliminary installers is that they are not signed.

> Thanks for all the progress on this!

You are welcome!

**Comment by Alizter** [comment] 2020-02-16 16:50
I'm closing this since we did update INSTALL.md with some (AFAIK) working instructions in #1189. We also have #1172 and a wiki page.

**Closed by Alizter** 2020-02-16 16:50 UTC
Labels: coq, windows
